development:
  adapter: postgresql
  encoding: unicode
  database: royal_developement
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: royal_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: royal_production
  pool: 5
  timeout: 5000
